name: Oscam CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - name: install dev packages
      run: |
        sudo apt-get -q update
        sudo apt-get install dialog xz-utils gawk subversion gcc make libusb-dev libusb-1.0-0 libusb-1.0-0-dev libssl-dev libpcsclite-dev libccid libc6-dev zlib1g-dev build-essential gcc-multilib module-assistant tofrodos sshpass openssl
    - name: build Oscam
      run: |
        echo compiling Oscam
        make USE_SSL=1 USE_LIBUSB=1
        echo done!
